### ISSUE TITLE
Could not find swtpm_cert in PATH.

### ISSUE THREAD

**Issue by SheetLightning** [stefanberger/swtpm#604]
**Describe the bug**
Thank you Firefox for loosing my carefully typed information! Aaaargh! Only just spent over half and hour typing it all up!

Ok, so here goes again.....

I am trying to set up a Windows 11 virtual machine in kvm/qemu using virt-manager. I ran into a problem in that the installer was telling me that my machine could not run Windows 11. One of the missing elements turns out to be TPM. So I added an emualted TPM2.0 device to the virtual machine only for it to generate an error telling me it could not find it. Eventually I found I needed to install swtpm, except that it was not available from the Mint repository. I asked on Mint support and they offered zich help as its not a Mint issue. I then tried to add the ppa to be met with various security errors so I abandoned that idea and decided to install from the source on GitHub. after cloning and trying to compile swtpm I ran into a missing dependency called libtmps which again, I could not find in the repository. So again I downloaded this from GitHub and compiled it. I was then able to finally compile swtp. Phew!

I then tried to run the Win11 virtual machine only to be met with an error telling me that it couldn't run swtpm. Having checked the log, the first error was:

Could not find certtool in PATH

This was easily fixed but installing gnutls-utils. Next I was met with:

Could not find swtpm_cert in PATH.
swtpm-localca exit with status 256: 

Using Google I found this:

https://github.com/stefanberger/swtpm/issues/463

Not quite the same issue, but I am unable to find swtpm-tools anywhere. Linux mint has a library called TPM2.0 utils in the repository but installing this did not help.
I have no idea what PATH is being referred to or where to find the cert that is being referred to.
Not sure what to do next.

**To Reproduce**
1. Create a new Windows virtual machine in kvm/qemu using virt-manager and attach the Windows 11 iso
2. Add a TPM2.0 software emulated CRB mode device to the virtual machine
3. Download and compile libtmps and swtpm
4. Try to run the virtual machine

**Expected behavior**
I expected the machine to start. From online sources it would appear that all the TPM stuff including any initialisation and necessary certificates being created would happen in the background automatically.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - virt-manager 2.2.1

**Versions of relevant components**
- swtpm: just downloaded - 0.6.1 ?
- libtpms: just downloaded - possibly 0.5.1 or 0.9.0 depending on source - Readme or web page
- openssl: 1.1.1f
- gnutls: no idea how to find this
- ...:

**Log files**
Please attach any log files. If using a VM and it was started with libvirt, attach the logfile  found in `/var/log/swtpm/libvirt/qemu/VM-NAME-swtpm.log`.

**Additional context**
Add any other context about the problem here
[Win11-Beta-swtpm.log](https://github.com/stefanberger/swtpm/files/7368193/Win11-Beta-swtpm.log)
![Screenshot from 2021-10-18 20-53-05](https://user-images.githubusercontent.com/58944011/137800331-a4ac6ec6-9e40-4ca5-9c4a-921949f4ccd9.png)
.

**Comment by stefanberger** [comment]
> I am uncertain what arguments I need to provide?

Try this:

```
mkdir /tmp/myvtpm
swtpm_setup --tpmstate /tmp/myvtpm --tpm2 --create-ek-cert --overwrite
```

**Comment by stefanberger** [comment]
> The problem now is determining why virt-manager is not generating a log. Without that it is difficult to know what is happening behind the scenes, if anything.

It's still not working? Are you accessing the VMs in system (as root) or session mode (as non-root)?

**Comment by stefanberger** [comment]
> Yes, that is correct.

If you are now running it in session mode (non-root) then your log file will be in `/home/john/.cache/libvirt/qemu/log/`. Previously you must have run it in system mode because of this error message hinting at `/var/log/swtpm/libvirt`:
```
libvirt.libvirtError: internal error: Could not run '/usr/local/bin/swtpm_setup'. exitstatus: 126; Check error log '/var/log/swtpm/libvirt/qemu/Win11-Beta-swtpm.log' for details
```

**Comment by stefanberger** [comment]
Did you solve the issue?

**Comment by stefanberger** [comment]
Has this issue been resolved in the meantime?

**Comment by mtreddy** [comment]
> So I see this error message here in the log:
> 
> ```
> Could not find swtpm_cert in PATH.
> ```
> 
> Did you compile swtpm_cert? Can you run this here from the swtpm checkout:
> 
> ```
> ./src/swtpm_cert/swtpm_cert --help
> ```
> 
> If not you will need to install the gnutls development package. It could be called libgnutls-dev on Linux Mint: https://community.linuxmint.com/software/view/libgnutls-dev
> 
> The run again:
> 
> ```
> ./autogen.sh --prefix ...
> ```
> 
> You need to see this here:
> 
> ```
> with_gnutls     :   yes  (no = swtpm_cert will NOT be built)
> ```

Thanks this is helpful

**Comment by ebakiris** [comment]
Hello. Although I followed the steps you mentioned here, still have the following output : 
`swtpm_localca exit with status 1: Could not find swtpm_cert in PATH`. I tried added to the path but the error still exists. I also tried to run the command `sudo swtpm_setup --tpmstate /tmp/myvtpm --tpm2 --create-ek-cert --overwrite` but nothing. Any idea? 
Note : When I am running `./src/swtpm_cert/swtpm_cert --help` I have the corresponding output.

**Comment by stefanberger** [comment]
> I have the corresponding output.

What is 'corresponding output'? Is the program available / did it get compiled? What is the output of 
```
echo $PATH; which swtpm_cert
```

**Comment by ebakiris** [comment]
Thanks for your quick answer, Stefan. I just found a had typo when adding the path of swtpm_cert in $PATH variable. My problem solved, i have the correct output 
`Starting vTPM manufacturing as ubuntu:ubuntu @ Thu 16 Feb 2023 02:27:47 PM UTC
TPM is listening on Unix socket.
Successfully created RSA 2048 EK with handle 0x81010001.
  Invoking /usr/bin/swtpm_localca --type ek --ek ab55ea42d22d536e9e798789aaa5535a95476495a7a5cab82493c17cec15e560e6813b04a87e340fd6918d7b10473a4be0d681be7eb577c94a6647d42ff2fac7a06a0b9c94adba469d388ce0d648313661b769b30ad6c8b2df26e8d0393a25db72ccf5c94bbb4ff5794734a83e0c6a75e2c014f7787d18f8122fe6a045001b28f5953a05e876b0062ed123449153dac1660a5fa8ed04b79bed761fa41e82fc264a54169d628c9b7dd837d06ba4c0f23f03d03ba6f7589ece3a145c44d1eec877e9786d2a48a4b472ed5c77c0e427195b069fa1730c6a3c406e8e53cc7b696ab483895d986934037ed86b97fef97e0d484547cda8145947f17e1d12f4daf42213 --dir /tmp/swtpm_setup.certs.82BI01 --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /home/ubuntu/.config/swtpm-localca.conf --optsfile /home/ubuntu/.config/swtpm-localca.options
swtpm_localca: Successfully created EK certificate locally.
Successfully created NVRAM area 0x1c00002 for RSA 2048 EK certificate.
Successfully created ECC EK with handle 0x81010016.
  Invoking /usr/bin/swtpm_localca --type ek --ek x=c7582325db7191c1b4de634b5ef106b4a6f6f1bb8026ea2670962ea1efee8c9bd931028a5d72e193729192af19b7b478,y=790b305ddc20e30eda70ffc193693010356c38f04f84c0d0b370c5570bccefcfca6460b5e666340b47dd290d87f2ece4,id=secp384r1 --dir /tmp/swtpm_setup.certs.82BI01 --tpm-spec-family 2.0 --tpm-spec-level 0 --tpm-spec-revision 164 --tpm-manufacturer id:00001014 --tpm-model swtpm --tpm-version id:20191023 --tpm2 --configfile /home/ubuntu/.config/swtpm-localca.conf --optsfile /home/ubuntu/.config/swtpm-localca.options
swtpm_localca: Successfully created EK certificate locally.
Successfully created NVRAM area 0x1c00016 for ECC EK certificate.
Successfully activated PCR banks sha256 among sha1,sha256,sha384,sha512.
Successfully authored TPM state.
Ending vTPM manufacturing @ Thu 16 Feb 2023 02:27:51 PM UTC`

**Comment by smallfishzzz** [comment]
with_gnutls     :    no  (no = swtpm_cert will NOT be built)

debian: 
sudo apt install gnutls-bin
