### ISSUE TITLE
Compiling swtpm-tpm2-preview.rev146.v2 

### ISSUE THREAD

**Issue by lm-bhaskins** [stefanberger/swtpm#73]
I am trying to build swtpm-tpm2-preview.rev146.v2 on RHEL7.4 with tpm2 support, and I am getting the following configure error:

./configure: line 13140: syntax error near unexpected token `libtpms_cryptolib,'
./configure: line 13140: `PKG_CHECK_VAR(libtpms_cryptolib, libtpms, cryptolib,'

I am running configure with the "--with-openssl --prefix=/usr" options. The latest libtpms (libtpms-tpm2-preview.rev146.v2) is installed with openssl support. I don't see any dependency in the documentation on cryptolib. What am I doing wrong?

**Comment by stefanberger** [comment]
I just pushed an update to the branch. It includes patch https://github.com/stefanberger/swtpm/commit/f2458ef7d692069ae3f07579c818f9440fd32403 that should fix the issue. Please give it a try.

**Comment by stefanberger** [comment]
Is this problem resolved now? It should be...

**Comment by lm-bhaskins** [comment]
Sorry for the delay. I haven't had a chance to test this and probably won't for a bit. I will close this and re-open an issue if I still can't get it to work.

Thanks!
