### ISSUE TITLE
SWTPM backup mechanism

### ISSUE THREAD

**Issue by Coffee-Processing-Unit** [stefanberger/swtpm#985]
Hello Stefan,

I am experiencing a problem similar to https://github.com/stefanberger/swtpm/issues/642.
The only solution I know of is removing the permall file, or replacing it with a working backup in case you don't want to lose all its data.

Do you have an existing backup mechanism for the permall file?
If not, I want to create one.

1. Can I backup the permall in the same directory the permall is written in?
2. What is the trigger for the backup? 
I noticed that the permall file is being written only at Windows startup (only very few times when doing other Windows TPM-related things). Is backing up after the VM was shut down enough?
Should the trigger be time-based and not event-based?
3. Do you have any other recommendations for creating the backup or for restoring from the backup?
4. In another subject, I suspect the permall corruption is due to a shutdown in the middle of Windows updates, what do you think? It may cause the permall to be partially written and hence to be corrupted.

Thank you

**Comment by stefanberger** [comment]
> * Can I backup the permall in the same directory the permall is written in?

That should be possible. swtpm will not remove the directory but management software may remove (typically only of VM is undefined)

> 
> * What is the trigger for the backup?
>   I noticed that the permall file is being written only at Windows startup (only very few times when doing other Windows TPM-related things). Is backing up after the VM was shut down enough?
>   Should the trigger be time-based and not event-based?

It may depend on which storage backend you are using. The directory backend rewrites all the state into a new temporary file before renaming it and replacing any existing file. The linear file backend works with memory mapping a file and cannot do the replacing of an existing file.

Obviously you don't want to make the backup exactly at the time the state file is re-written, so the safest time to do the backup is when you are sure that the TPM is not being used, which would be when the VM is off or paused. If you were to quiesce the VM,  for example by pausing it, you could do the backup then. 

> 
> * Do you have any other recommendations for creating the backup or for restoring from the backup?

I don't have any other recommendations.

> 
> * In another subject, I suspect the permall corruption is due to a shutdown in the middle of Windows updates, what do you think? It may cause the permall to be partially written and hence to be corrupted.

Something would have to abruptly terminate swtpm for corruption to happen and it would likely only happen with the file backend that's using mmap'ing.

**Comment by Coffee-Processing-Unit** [comment]
1. Can the aforementioned corruption in swtpm happen during the time the VM is powered on? Does the permall file written also when the VM is powered on?
2. Can you please explain why the atomic writing mechanism doesn't defend against mmaping file backends? Will replacing the mmapping file backend with another one prevent the corruptions?

**Comment by stefanberger** [comment]
> 1. Can the aforementioned corruption in swtpm happen during the time the VM is powered on? Does the permall file written also when the VM is powered on?

Normally nothing would corrupt the state unless swtpm gets abruptly terminated.
The permall file is ONLY (re-)written when the VM is powered on. If you for example define an NVRAM area, it will rewrite the permall file.

> 
>     2. Can you please explain why the atomic writing mechanism doesn't defend against mmaping file backends? 

I am not understanding the question. There are two distinct storage backends, one is called the file backend ( backend-uri=file://<path_to_dir>   see swtpm man page) and the other one the directory backend ( backend-uri=dir://<path_to_dir>). Both have different implementations as described previously.

> Will replacing the mmapping file backend with another one prevent the corruptions?

Which one of the two are you using? 
As I said, you would have to abruptly terminate swtpm to cause the corruption. Are you doing this?

**Comment by Coffee-Processing-Unit** [comment]
1. Why only writing the peramll when powering on the VM? What is the source of the data? do you save it to swtpm's memory when the VM is shutting down and then write it to disk on power up?

I once saw the permall was being written while I set Windows Hello PIN, what can be the reason for this?
2. I'm using the --tpmstate dir=<>,mode=<> syntax, not the backend-uri= syntax.
I asked you about the file backend because you said:

> Something would have to abruptly terminate swtpm for corruption to happen and it would likely only happen with the file backend that's using mmap'ing.

So maybe changing the file backup can prevent corruption.

3. I'm not terminating the swtpm on purpose - but I do force shutdown of the computer sometimes. Can this effect?
The size of the permall file is 0 when this error occurs.
In which way do you check the consistency of the TMP2-00.permall file before renaming it to tpm2-00.permall?

**Comment by stefanberger** [comment]
> I once saw the permall was being written while I set Windows Hello PIN, what can be the reason for this?

Maybe a key was created that was stored in the TPM. But this is just a guess.

> So maybe changing the file backup can prevent corruption.

What does 'changing the file backup' mean? I really doubt that you can easily cause corruption.


> 3\. I'm not terminating the swtpm on purpose - but I do force shutdown of the computer sometimes. Can this effect?

You force-shutdown a VM or you force-off power on your computer where the VM is running on?

>         The size of the permall file is 0 when this error occurs. When can this happen?
>         In which way do you check the consistency of the TMP2-00.permall file before renaming it to tpm2-00.permall?

Here's the `rename`: https://github.com/stefanberger/swtpm/blob/master/src/swtpm/swtpm_nvstore_dir.c#L474

At this point the data have been written to the kernel. Unless you now abruptly power off the host, the bytes will make it into the filesystem.

**Comment by Coffee-Processing-Unit** [comment]
> Maybe a key was created that was stored in the TPM. But this is just a guess.

If so, the permall file can be written other times than when the VM is powered on?
Can you please explain more about the architecture with a focus on the writing process? 
What is the data flow between the char device, the NVRAM, the OS, and the permall file?

***

> What does 'changing the file backup' mean? I doubt that you can easily cause corruption.

Sorry, I meant to change the file backend, because you said:

> The linear file backend works with memory mapping a file and cannot do the replacing of an existing file.
> Something would have to abruptly terminate swtpm for corruption to happen and it would likely only happen with the file backend that's using mmap'ing.
> 
So will changing to a file backend that is not using mmaping can prevent the corruption?

***

> You force-shutdown a VM or you force-off power on your computer where the VM is running on?

The whole computer, not just the VM

***

> Here's the rename: https://github.com/stefanberger/swtpm/blob/master/src/swtpm/swtpm_nvstore_dir.c#L474
> At this point the data have been written to the kernel. Unless you now abruptly power off the host, the bytes will make it into the physical filesystem.

I see that there is no check for the consistency of the data you are writing, and just writing everything received from the NVRAM. What do you think of adding such a check? Is there a way to prevent from emptying the file when there wasn't an intention to do it? this will prevent the corruption I'm experiencing.

**Comment by stefanberger** [comment]
> > Maybe a key was created that was stored in the TPM. But this is just a guess.
> 
> If so, the permall file can be written other times than when the VM is powered on? Can you please explain more about the architecture with a focus on the writing process? What is the data flow between the char device, the NVRAM, the OS, and the permall file?


The permall file can be rewritten at any time that apps are using the TPM 2. It depends on what commands the apps are sending, though. Some cause the permall file to be rewritten, others don't. There are more than 100 commands in the TPM 2 and we would have to go through all of them and discuss the circumstances that each one can cause changes to the permall file. But defining or undefining or writing to an NVRAM area causes changes to the permanent state, so permall will be re-written. The same is true when keys are persisted or removed from persistent storage.

> 
> > What does 'changing the file backup' mean? I doubt that you can easily cause corruption.
> 
> Sorry, I meant to change the file backend, because you said:
> 
> > The linear file backend works with memory mapping a file and cannot do the replacing of an existing file.
> > Something would have to abruptly terminate swtpm for corruption to happen and it would likely only happen with the file backend that's using mmap'ing.
> 
> So will changing to a file backend that is not using mmaping can prevent the corruption?

It's far less likely I would say.

> 
> > You force-shutdown a VM or you force-off power on your computer where the VM is running on?
> 
> The whole computer, not just the VM

So you want to cause filesystem corruption as well?

> 
> > Here's the rename: https://github.com/stefanberger/swtpm/blob/master/src/swtpm/swtpm_nvstore_dir.c#L474
> > At this point the data have been written to the kernel. Unless you now abruptly power off the host, the bytes will make it into the physical filesystem.
> 
> I see that there is no check for the consistency of the data you are writing, and just writing everything received from the NVRAM. What do you think of adding such a check? Is there a way to prevent from emptying the file when there wasn't an intention to do it? this will prevent the corruption I'm experiencing.

- Can you explain what checks should be done?
- Which file is being emptied? No file is ever being emptied as far as I know.

**Comment by Coffee-Processing-Unit** [comment]
> The permall file is ONLY (re-)written when the VM is powered on. If you for example define an NVRAM area, it will rewrite the permall file.

> But defining or undefining or writing to an NVRAM area causes changes to the permanent state, so permall will be re-written.

> Some cause the permall file to be rewritten, others don't

How does the write on startup different from writing when the vm is already powered on?
what do you mean by '(re-)written when the VM is powered on'?  <br /> Are you saving data in the nvram when shutting down and writing it to the permall only on vm startup?
Does it mean the file system data is not up to date until vm start?

---
> So you want to cause filesystem corruption as well?

I want to handle the case the computer must be hard-shutdown.

---
> Can you explain what checks should be done?

before writing data from the nvram to the filesystem, check if the data being written (filedata) is empty:
https://github.com/stefanberger/swtpm/blob/58c9549cdc815347567d5ae441b72341c50db5e0/src/swtpm/swtpm_nvstore_dir.c#L438

> Which file is being emptied? No file is ever being emptied as far as I know.

The permall file is being emptied

---

is the directory /var/lib/libvirt/swtpm/ being deleted sometime in the life of the swtpm? or just when uninstalling libvirt?

**Comment by stefanberger** [comment]
> > The permall file is ONLY (re-)written when the VM is powered on. If you for example define an NVRAM area, it will rewrite the permall file.
> 
> > But defining or undefining or writing to an NVRAM area causes changes to the permanent state, so permall will be re-written.
> 
> > Some cause the permall file to be rewritten, others don't
> 

FYI: Here's the spec that enumerates all the commands of a TPM 2. Have a look!   https://trustedcomputinggroup.org/wp-content/uploads/Trusted-Platform-Module-2.0-Library-Part-3-Commands-Version-184-rc2_20Dec24.pdf

> How does the write on startup different from writing when the vm is already powered on? 

There's no difference between these writes. libtpms collects the TPM 2's state and passes it back to swtpm and swtpm writes it into the storage backend.

> what do you mean by '(re-)written when the VM is powered on'? Are you saving data in the nvram when shutting down and writing it to the permall only on vm startup? 

When an application for example executes the TPM 2 command TPM2_NV_DefineSpace  then this will cause the TPM 2 state to be rewritten if a new NVRAM area was defined by this command.

>Does it mean the file system data is not up to date until vm start? How do you validate you finished writing all the data before the VM is powered on? Can it cause race conditions?

No, the data will have been written to the filesystem before the result of the command TPM2_NV_DefineSpace has been passed back to the application. It doesn't mean that the data has been written to the physical disk, yet, since the OS filesystem driver may not have been able to write it to disk, yet, but at least the filesystem has the data and will write them out asap.

> 
> > Some cause the permall file to be rewritten, others don't
> 
> If a TPM command doesn't cause the permall file to change right away, will it be at some stage in the future?

Every TPM command that requires the permall file to be written again to disk will do this immediately and before the result is returned to the TPM driver / application.

> 
> > So you want to cause filesystem corruption as well?
> 
> I want to handle the case the computer must be hard-shutdown.

There are journaling filesystems out there that can handle such cases but they may have their limits as well. I do not know the details of their limits, though.  In the best case a file containing old data may be there, in the worst case some corruption may occur.

> 
> > Something would have to abruptly terminate swtpm for corruption to happen and it would likely only happen with the file backend that's using mmap'ing.
> > you would have to abruptly terminate swtpm to cause the corruption
> 
> Can you please explain why abruptly terminating the swtpm will cause the corruption? Why don't the swtpm hard-shutdown safe?

The directory storage backend writes a temporary file first before it renames it and replaces the regular TPM 2 permall file. The temporary file is written in the usual open+write+close sequence and an abrupt termination here may cause this file to not be valid but the final file hasn't been touched. No corruption should occur.

> 
> > Can you explain what checks should be done?
> 
> before writing data from the nvram to the filesystem, check if the data being written (filedata) is empty:

No zero-size data buffer is written to the TPM 2 state file, ever. For example, a header is always prepended, and if swtpm was to run out of memory, the state would not be written at all.

https://github.com/stefanberger/swtpm/blob/master/src/swtpm/swtpm_nvstore.c#L409-L416

> 
> [swtpm/src/swtpm/swtpm_nvstore_dir.c](https://github.com/stefanberger/swtpm/blob/58c9549cdc815347567d5ae441b72341c50db5e0/src/swtpm/swtpm_nvstore_dir.c#L438)
> 
> Line 438 in [58c9549](/stefanberger/swtpm/commit/58c9549cdc815347567d5ae441b72341c50db5e0)
>  lrc = write_full(fd, filedata, filedata_length); 
> 
> > Which file is being emptied? No file is ever being emptied as far as I know.
> 
> The permall file is being emptied
> 
> is the directory /var/lib/libvirt/swtpm/ being deleted sometime in the life of the swtpm? or just when uninstalling libvirt?

swtpm doesn't delete the directory, only libvirt does this upon VM undefine.

**Comment by Coffee-Processing-Unit** [comment]
> swtpm doesn't delete the directory, only libvirt does this upon VM undefined.

When I define any VM in the system and left without VMs, libvirt still doesn't delete this folder
Does this make sense?

---

> FYI: Here's the spec that enumerates all the commands of a TPM 2. Have a look! https://trustedcomputinggroup.org/wp-content/uploads/Trusted-Platform-Module-2.0-Library-Part-3-Commands-Version-184-rc2_20Dec24.pdf

Thank you! I will reference it.

---

> The directory storage backend writes a temporary file first before it renames it and replaces the regular TPM 2 permall file. The temporary file is written in the usual open+write+close sequence and an abrupt termination here may cause this file to not be valid but the final file hasn't been touched. No corruption should occur.

I understand. Thank you for the rest of the explanations and all of your help. I understand the situation I describe can't be explained, and still, corruption occurs more times than it can be ignored.
And it probably didn't happen only to me - https://github.com/stefanberger/swtpm/issues/642
The problem is that it occurs rarely so it's hard to catch to debug. 
Are there some logging tools you recommend to leave running in the system so that when the bug occurs I can have more data about it? Again, the only symptom is that the size of the permall file is 0.

**Comment by stefanberger** [comment]
> When I define any VM in the system and left without VMs, libvirt still doesn't delete this folder

What does this mean? Are you undefining VMs?

> And it probably didn't happen only to me - https://github.com/stefanberger/swtpm/issues/642

#642 has been resolved afaik and it had something to do with swtpm_setup. I don't see how your issue relates to this one.

> Are there some logging tools you recommend to leave running in the system so that when the bug occurs I can have more data about it? Again, the only symptom is that the size of the permall file is 0.

I am not aware of any such logging tools. 

Due to the reason explained previously, I do not see how the permall file can be 0 unless you cause corruption by pulling the power plug at the exactly the right time, which probably is a challenge by itself. When the temporary file is written, return codes are checked and the renaming of the file would only happen if the temporary file could be written and closed successfully.

**Comment by Coffee-Processing-Unit** [comment]
> > When I define any VM in the system and left without VMs, libvirt still doesn't delete this folder
> 
> What does this mean? Are you undefining VMs?

Sorry, I meant that when I **undefine** any VM in the system and left without VMs, libvirt still doesn't delete this folder

> Due to the reason explained previously, I do not see how the permall file can be 0 unless you cause corruption by pulling the power plug at the exactly the right time, which probably is a challenge by itself. When the temporary file is written, return codes are checked and the renaming of the file would only happen if the temporary file could be written and closed successfully.

This is exactly what I'm looking for: what can be this exact right time, that willl cause the corruption of the swtpm? What is the state of the system at this time?

**Comment by stefanberger** [comment]
> 
> > Due to the reason explained previously, I do not see how the permall file can be 0 unless you cause corruption by pulling the power plug at the exactly the right time, which probably is a challenge by itself. When the temporary file is written, return codes are checked and the renaming of the file would only happen if the temporary file could be written and closed successfully.
> 
> This is exactly what I'm looking for: what can be this exact right time, that willl cause the corruption of the swtpm? What is the state of the system at this time?

You may want to refer to the last paragraph in this comment: https://github.com/stefanberger/swtpm/issues/985#issuecomment-2758250366

**Comment by stefanberger** [comment]
#1002 should help address this issue.

**Comment by stefanberger** [comment]
@Coffee-Processing-Unit, you should try/look at PR #1002 and see whether this resolves your issue. The implementation is my best guess at resolving it. I cannot say what would happen if power was turned off while the backup file is created and the new file is written, whether at least one of the files will be in good condition once the system comes back.
